# Generated by Django 5.1.2 on 2024-10-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats_missions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spycat',
            old_name='salart',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='spycat',
            old_name='year_of_experience',
            new_name='years_of_experience',
        ),
    ]
