# Generated by Django 5.1.2 on 2024-10-30 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_missions', '0004_alter_target_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cats_missions.spycat'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='target',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
